# Generated by Django 4.2.14 on 2024-11-15 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='caregiver',
            field=models.ForeignKey(limit_choices_to={'role': 'CG'}, on_delete=django.db.models.deletion.CASCADE, related_name='account_icons', to='accounts.userprofile'),
        ),
    ]
