# Generated by Django 4.2.14 on 2024-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icon',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
