# Generated by Django 4.2.14 on 2024-11-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('communication', '0002_icon_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='caregiver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CG'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='accounts.userprofile'),
        ),
    ]
