# Generated by Django 4.2.14 on 2024-11-15 10:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_icon_caregiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
