# Generated by Django 4.2.14 on 2024-11-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_icon_caregiver'),
        ('communication', '0004_alter_icon_image'),
    ]

    operations = [
    ]
