# Generated by Django 4.2.14 on 2024-11-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('caregiver', models.ForeignKey(limit_choices_to={'role': 'CG'}, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='accounts.userprofile')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='communication.icon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='accounts.userprofile')),
            ],
        ),
    ]
