# Generated by Django 4.2.14 on 2024-11-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('communication', '0005_merge_0002_alter_icon_caregiver_0004_alter_icon_image'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='caregiver',
            field=models.ForeignKey(help_text='The caregiver receiving the notification.', limit_choices_to={'role': 'CG'}, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='icon',
            field=models.ForeignKey(blank=True, help_text='The icon selected by the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='communication.icon'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False, help_text='Whether the notification has been sent.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notified_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The time when the notification was created.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(help_text='The user who triggered the notification.', limit_choices_to={'role': 'USER'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='accounts.userprofile'),
        ),
    ]
